# Generated by Django 4.0.4 on 2022-07-08 17:02

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import mfestival_api.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField(default='')),
                ('date_contacted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='gallery')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adult', 'Adult'), ('Adventure', 'Adventure'), ("Children's/Family", "Children's/Family"), ('Comedy', 'Comedy'), ('Comedy Drama', 'Comedy Drama'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Epic', 'Epic'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Horror', 'Horror'), ('Musical', 'Musical'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Spy', 'Spy'), ('Thriller', 'Thriller'), ('War', 'War'), ('Other', 'Other')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JoinBsiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('Documentary Film', 'Documentary Film'), ('Feature Film', 'Feature Film'), ('Short Film', 'Short Film'), ('Student Film', 'Student Film'), ('Women in Film', 'Women in Film'), ('Animated Film', 'Animated Film'), ('African Films', 'African Films')], max_length=70)),
                ('poster', models.ImageField(blank=True, upload_to='event_pics')),
                ('views', models.IntegerField(default=0)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('directors', models.TextField(blank=True)),
                ('writers', models.TextField(blank=True)),
                ('producers', models.TextField(blank=True)),
                ('key_casts', models.TextField(blank=True)),
                ('about_submitter', models.TextField(blank=True)),
                ('movie_link', models.URLField(blank=True)),
                ('user_score', models.IntegerField(default=0)),
                ('trailer', models.FileField(blank=True, upload_to='trailers', validators=[mfestival_api.validators.validate_trailer_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mpeg', 'mp4', 'mov'])])),
                ('slug', models.SlugField(blank=True, default='', max_length=100)),
                ('selected', models.BooleanField(default=False)),
                ('full_movie', models.FileField(blank=True, max_length=255, null=True, upload_to='movies')),
                ('festival_date', models.DateField(auto_now_add=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
