# Generated by Django 4.0.4 on 2022-06-06 09:46

from django.db import migrations, models
import mfestival_api.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('Documentary Film', 'Documentary Film'), ('Feature Film', 'Feature Film'), ('Feature Film', 'Feature Film'), ('Short Film', 'Short Film'), ('Student Film', 'Student Film'), ('Women in Film', 'Women in Film'), ('Animated Film', 'Animated Film'), ('African Films', 'African Films'), ('Music Video', 'Music Video')], max_length=70)),
                ('poster', models.ImageField(upload_to='official_posters')),
                ('views', models.IntegerField(default=0)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.CharField(blank=True, max_length=100)),
                ('trailer', models.CharField(blank=True, max_length=100, validators=[mfestival_api.validators.validate_trailer_size])),
                ('slug', models.SlugField(default='', max_length=100)),
                ('selected', models.BooleanField(default=False)),
                ('festival_date', models.DateField(auto_now_add=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
