# Generated by Django 4.0.4 on 2022-07-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adult', 'Adult'), ('Adventure', 'Adventure'), ("Children's/Family", "Children's/Family"), ('Comedy', 'Comedy'), ('Comedy Drama', 'Comedy Drama'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Epic', 'Epic'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Horror', 'Horror'), ('Musical', 'Musical'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Spy', 'Spy'), ('Thriller', 'Thriller'), ('War', 'War'), ('Other', 'Other')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='submitfilm',
            name='about_submitter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submitfilm',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submitfilm',
            name='directors',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submitfilm',
            name='key_casts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submitfilm',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submitfilm',
            name='producers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submitfilm',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submitfilm',
            name='writers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submitfilm',
            name='genres',
            field=models.ManyToManyField(blank=True, to='mfestival_api.genres'),
        ),
    ]
