# Generated by Django 4.0.4 on 2022-07-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0002_genres_submitfilm_about_submitter_submitfilm_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitfilm',
            name='genres',
        ),
    ]
