# Generated by Django 4.0.4 on 2022-07-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0002_alter_submitfilm_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfilm',
            name='poster',
            field=models.ImageField(blank=True, default='video-player.png', upload_to='event_pics'),
        ),
    ]
