# Generated by Django 4.0.4 on 2022-07-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0003_remove_submitfilm_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfilm',
            name='directors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submitfilm',
            name='producers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submitfilm',
            name='writers',
            field=models.TextField(blank=True),
        ),
    ]
