# Generated by Django 4.0.4 on 2022-07-03 08:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0004_alter_submitfilm_directors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfilm',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
