# Generated by Django 4.0.4 on 2022-07-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0006_submitfilm_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfilm',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
