# Generated by Django 4.0.4 on 2022-07-03 12:58

import django.core.validators
from django.db import migrations, models
import mfestival_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0008_submitfilm_movie_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfilm',
            name='poster',
            field=models.ImageField(blank=True, upload_to='event_pics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='submitfilm',
            name='trailer',
            field=models.CharField(blank=True, max_length=100, validators=[mfestival_api.validators.validate_trailer_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mpeg', 'mp4', 'mov'])]),
        ),
    ]
