# Generated by Django 4.0.4 on 2022-07-03 13:10

import django.core.validators
from django.db import migrations, models
import mfestival_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0009_alter_submitfilm_poster_alter_submitfilm_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfilm',
            name='trailer',
            field=models.FileField(blank=True, upload_to='', validators=[mfestival_api.validators.validate_trailer_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mpeg', 'mp4', 'mov'])]),
        ),
    ]
