# Generated by Django 4.0.4 on 2022-07-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0010_alter_submitfilm_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitfilm',
            name='release_date',
        ),
    ]
