# Generated by Django 4.0.4 on 2022-07-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0012_alter_submitfilm_movie_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitfilm',
            name='full_movie',
            field=models.FileField(blank=True, null=True, upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='submitfilm',
            name='poster',
            field=models.ImageField(blank=True, upload_to='event_pics'),
        ),
    ]
