# Generated by Django 4.0.4 on 2022-07-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0013_submitfilm_full_movie_alter_submitfilm_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfilm',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
    ]
