# Generated by Django 4.0.4 on 2022-07-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0014_alter_submitfilm_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfilm',
            name='full_movie',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='movies'),
        ),
    ]
