# Generated by Django 4.0.4 on 2022-07-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0017_alter_contactus_mobile_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
