# Generated by Django 4.0.4 on 2022-07-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0018_contactus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='mobile_num',
            field=models.CharField(max_length=13),
        ),
    ]
