# Generated by Django 4.0.4 on 2022-07-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0019_alter_contactus_mobile_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='mobile_num',
        ),
    ]
