# Generated by Django 4.0.4 on 2022-07-08 10:40

import django.core.validators
from django.db import migrations, models
import mfestival_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_api', '0021_joinbsiff_contactus_date_contacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfilm',
            name='trailer',
            field=models.FileField(blank=True, upload_to='trailers', validators=[mfestival_api.validators.validate_trailer_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mpeg', 'mp4', 'mov'])]),
        ),
    ]
