# Generated by Django 4.0.4 on 2022-05-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfestival_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Fnet User', max_length=150, unique=True),
        ),
    ]
